---

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker OS package dependencies
  become: true
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Import Docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu version name
  command: "lsb_release -cs"
  register: release_output

- debug: msg="release name='{{ release_output.stdout }}'"

- name: Install Docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ release_output.stdout }} stable
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
