---

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Update all OS packages
  become: true
  apt:
    state: latest
    name: "*"

- name: Install base packages
  become: true
  apt:
    state: present
    name:
      - curl
      - e2fsprogs
      - make
      - gcc
      - g++
      - git
      - lsscsi
      - mercurial
      - multipath-tools
      - nfs-common
      - open-iscsi
      - python3
      - python3-pip
      - screen
      - scsitools
      - sg3-utils
      - vim
      - wireshark
      - xfsprogs
      - gpg
      - golang
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - net-tools
